#!/usr/bin/env -S uv run --quiet
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "psycopg[binary]>=3.1",
# ]
# ///
"""Replace the 12 generic synthetic SKUs with the real FGF Brands catalog.

The synthetic seed in infra/supabase/seed.sql carries 12 generic SKU IDs
(sku-blueberry-muffin-4pk, sku-choc-chip-cookie-12pk, ...). FGF Brands
publishes a clear public brand portfolio across six labels:

  - ACE Bakery       -- baguettes, focaccia, ciabatta, sourdough
                       (acebakery.com -- product mentions verified 2026-05)
  - Stonefire        -- naan, naan dippers, mini naan, pizza crusts
                       (stonefire.com -- product mentions verified 2026-05)
  - Wonder Bread     -- sliced classic loaves
                       (City of Pickering / Baking Business press releases)
  - D'Italiano       -- buns and rolls (same source)
  - Country Harvest  -- whole-grain sliced breads (same source)
  - Casa Mendosa     -- tortillas (same source)

This script swaps in 12 real branded SKUs with realistic categories,
allergens, margins, and shelf life, and rewires production_formulas +
the seeded retailer_orders to reference them.

Cascade (the new IDs are different from the old, so this is destructive):
  1. DELETE demand_forecasts rows pointing at old SKUs
       (runtime-generated by F2.8; will regenerate next forecast pass)
  2. DELETE seeded retailer_orders rows pointing at old SKUs
       (the 8 rows from infra/supabase/seed.sql)
  3. DELETE production_formulas rows pointing at old SKUs
       (the ~60 rows from infra/supabase/seed.sql)
  4. DELETE the 12 old skus rows themselves
  5. INSERT the 12 new branded skus
  6. INSERT the new production_formulas (3-6 ingredients per SKU; only
     references ingredients already in the seed -- no new ingredients)
  7. INSERT the 8 retailer_orders, mapped to keep the retailer-tier mix
     (Costco bulk staples, Walmart staples, Loblaws mid, Whole Foods premium)

The script is idempotent: re-running after a successful pass is a no-op
because the old SKU IDs no longer exist.

Usage:
  uv run infra/seed_toronto_skus.py             # apply cascade
  uv run infra/seed_toronto_skus.py --dry-run   # print plan, do not write
"""

from __future__ import annotations

import argparse
import os
from collections import Counter
from datetime import date

import psycopg

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://bakery:bakery@localhost:5432/bakery",
)

# The 12 generic SKU IDs from the original infra/supabase/seed.sql block.
# Removed (along with their dependents) before the new branded catalog lands.
LEGACY_SKU_IDS = (
    "sku-blueberry-muffin-4pk",
    "sku-lemon-poppy-muffin-4pk",
    "sku-choc-chip-muffin-4pk",
    "sku-banana-bread-loaf",
    "sku-cinnamon-roll-6pk",
    "sku-croissant-butter-4pk",
    "sku-bagel-plain-6pk",
    "sku-bagel-sesame-6pk",
    "sku-sourdough-loaf",
    "sku-choc-chip-cookie-12pk",
    "sku-oatmeal-cookie-12pk",
    "sku-almond-danish-4pk",
)

# 12 branded SKUs across the six FGF labels. Allergen tags pulled from each
# brand's published ingredient lists or the obvious (gluten in everything wheat,
# dairy in naan/croissants per recipe convention).
TORONTO_SKUS: list[dict] = [
    # --- ACE Bakery (acebakery.com) ---
    {
        "sku_id":          "sku-ace-baguette-classic",
        "name":            "ACE White Baguette",
        "category":        "bread",
        "margin_per_unit": 1.65,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 4,
        "brand":           "ACE Bakery",
    },
    {
        "sku_id":          "sku-ace-rustic-italian-oval",
        "name":            "ACE Rustic Italian Oval Loaf",
        "category":        "bread",
        "margin_per_unit": 1.85,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 5,
        "brand":           "ACE Bakery",
    },
    {
        "sku_id":          "sku-ace-rosemary-focaccia",
        "name":            "ACE Rosemary Focaccia",
        "category":        "bread",
        "margin_per_unit": 2.10,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 4,
        "brand":           "ACE Bakery",
    },
    {
        "sku_id":          "sku-ace-ciabatta-piccolo-6pk",
        "name":            "ACE Ciabatta Piccolo 6-pack",
        "category":        "bread",
        "margin_per_unit": 1.55,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 5,
        "brand":           "ACE Bakery",
    },
    {
        "sku_id":          "sku-ace-sourdough-bistro",
        "name":            "ACE Sourdough Bistro Loaf",
        "category":        "bread",
        "margin_per_unit": 1.95,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 6,
        "brand":           "ACE Bakery",
    },

    # --- Stonefire (stonefire.com) ---
    {
        "sku_id":          "sku-stonefire-original-naan-2pk",
        "name":            "Stonefire Original Naan 2-pack",
        "category":        "flatbread",
        "margin_per_unit": 1.40,
        "allergen_tags":   ["gluten", "dairy"],
        "shelf_life_days": 7,
        "brand":           "Stonefire",
    },
    {
        "sku_id":          "sku-stonefire-mini-naan-8pk",
        "name":            "Stonefire Mini Naan 8-pack",
        "category":        "flatbread",
        "margin_per_unit": 1.60,
        "allergen_tags":   ["gluten", "dairy"],
        "shelf_life_days": 7,
        "brand":           "Stonefire",
    },
    {
        "sku_id":          "sku-stonefire-naan-dippers-original",
        "name":            "Stonefire Naan Dippers Original",
        "category":        "flatbread",
        "margin_per_unit": 1.30,
        "allergen_tags":   ["gluten", "dairy"],
        "shelf_life_days": 14,
        "brand":           "Stonefire",
    },
    {
        "sku_id":          "sku-stonefire-pizza-crust-2pk",
        "name":            "Stonefire Artisan Pizza Crust 2-pack",
        "category":        "flatbread",
        "margin_per_unit": 1.75,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 14,
        "brand":           "Stonefire",
    },

    # --- Wonder, D'Italiano, Country Harvest (sliced bread family) ---
    {
        "sku_id":          "sku-wonder-classic-white-loaf",
        "name":            "Wonder Classic White Bread",
        "category":        "bread",
        "margin_per_unit": 0.85,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 7,
        "brand":           "Wonder",
    },
    {
        "sku_id":          "sku-d-italiano-hot-dog-buns-8pk",
        "name":            "D'Italiano Hot Dog Buns 8-pack",
        "category":        "bread",
        "margin_per_unit": 1.05,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 7,
        "brand":           "D'Italiano",
    },
    {
        "sku_id":          "sku-country-harvest-12-grain-loaf",
        "name":            "Country Harvest 12 Grain Bread",
        "category":        "bread",
        "margin_per_unit": 1.25,
        "allergen_tags":   ["gluten"],
        "shelf_life_days": 7,
        "brand":           "Country Harvest",
    },
]

# Bill of materials per SKU. Every ingredient_id below already exists in
# infra/supabase/seed.sql -- this script never adds new ingredients. kg_per_unit
# is per package (i.e. per "unit" as recorded in production_schedules), so a
# 6-pack carries 6x the per-loaf weight.
TORONTO_FORMULAS: list[tuple[str, str, float]] = [
    # ACE White Baguette (single ~250g baguette)
    ("sku-ace-baguette-classic",       "ing-flour-bread",        0.180),
    ("sku-ace-baguette-classic",       "ing-yeast-instant",      0.003),
    ("sku-ace-baguette-classic",       "ing-salt-kosher",        0.004),

    # ACE Rustic Italian Oval (single ~500g loaf)
    ("sku-ace-rustic-italian-oval",    "ing-flour-bread",        0.350),
    ("sku-ace-rustic-italian-oval",    "ing-flour-whole-wheat",  0.060),
    ("sku-ace-rustic-italian-oval",    "ing-yeast-instant",      0.005),
    ("sku-ace-rustic-italian-oval",    "ing-salt-kosher",        0.008),
    ("sku-ace-rustic-italian-oval",    "ing-oil-vegetable",      0.020),

    # ACE Rosemary Focaccia (single ~450g flat loaf)
    ("sku-ace-rosemary-focaccia",      "ing-flour-bread",        0.320),
    ("sku-ace-rosemary-focaccia",      "ing-yeast-instant",      0.005),
    ("sku-ace-rosemary-focaccia",      "ing-salt-sea",           0.008),
    ("sku-ace-rosemary-focaccia",      "ing-oil-vegetable",      0.045),

    # ACE Ciabatta Piccolo 6-pack (6x ~85g rolls)
    ("sku-ace-ciabatta-piccolo-6pk",   "ing-flour-bread",        0.420),
    ("sku-ace-ciabatta-piccolo-6pk",   "ing-yeast-instant",      0.006),
    ("sku-ace-ciabatta-piccolo-6pk",   "ing-salt-kosher",        0.010),
    ("sku-ace-ciabatta-piccolo-6pk",   "ing-oil-vegetable",      0.025),

    # ACE Sourdough Bistro (single ~600g loaf)
    ("sku-ace-sourdough-bistro",       "ing-flour-bread",        0.450),
    ("sku-ace-sourdough-bistro",       "ing-flour-whole-wheat",  0.090),
    ("sku-ace-sourdough-bistro",       "ing-salt-kosher",        0.011),
    ("sku-ace-sourdough-bistro",       "ing-yeast-active-dry",   0.004),

    # Stonefire Original Naan 2-pack (2x ~110g pieces; cultured-milk dough)
    ("sku-stonefire-original-naan-2pk","ing-flour-ap",           0.180),
    ("sku-stonefire-original-naan-2pk","ing-yogurt-plain",       0.040),
    ("sku-stonefire-original-naan-2pk","ing-milk-whole",         0.030),
    ("sku-stonefire-original-naan-2pk","ing-yeast-instant",      0.003),
    ("sku-stonefire-original-naan-2pk","ing-salt-kosher",        0.004),
    ("sku-stonefire-original-naan-2pk","ing-oil-vegetable",      0.012),

    # Stonefire Mini Naan 8-pack (8x ~45g rounds)
    ("sku-stonefire-mini-naan-8pk",    "ing-flour-ap",           0.300),
    ("sku-stonefire-mini-naan-8pk",    "ing-yogurt-plain",       0.060),
    ("sku-stonefire-mini-naan-8pk",    "ing-milk-whole",         0.045),
    ("sku-stonefire-mini-naan-8pk",    "ing-yeast-instant",      0.005),
    ("sku-stonefire-mini-naan-8pk",    "ing-salt-kosher",        0.006),

    # Stonefire Naan Dippers Original (~225g bag of crispy strips)
    ("sku-stonefire-naan-dippers-original","ing-flour-ap",       0.200),
    ("sku-stonefire-naan-dippers-original","ing-milk-powder",    0.012),
    ("sku-stonefire-naan-dippers-original","ing-yeast-instant",  0.003),
    ("sku-stonefire-naan-dippers-original","ing-salt-kosher",    0.004),
    ("sku-stonefire-naan-dippers-original","ing-oil-vegetable",  0.018),

    # Stonefire Artisan Pizza Crust 2-pack (2x ~200g par-baked rounds)
    ("sku-stonefire-pizza-crust-2pk",  "ing-flour-bread",        0.300),
    ("sku-stonefire-pizza-crust-2pk",  "ing-yeast-instant",      0.005),
    ("sku-stonefire-pizza-crust-2pk",  "ing-salt-kosher",        0.006),
    ("sku-stonefire-pizza-crust-2pk",  "ing-oil-vegetable",      0.015),

    # Wonder Classic White Bread (single 675g loaf)
    ("sku-wonder-classic-white-loaf",  "ing-flour-ap",           0.420),
    ("sku-wonder-classic-white-loaf",  "ing-sugar-granulated",   0.030),
    ("sku-wonder-classic-white-loaf",  "ing-yeast-instant",      0.006),
    ("sku-wonder-classic-white-loaf",  "ing-salt-kosher",        0.009),
    ("sku-wonder-classic-white-loaf",  "ing-oil-vegetable",      0.020),

    # D'Italiano Hot Dog Buns 8-pack (8x ~50g buns)
    ("sku-d-italiano-hot-dog-buns-8pk","ing-flour-bread",        0.260),
    ("sku-d-italiano-hot-dog-buns-8pk","ing-sugar-granulated",   0.025),
    ("sku-d-italiano-hot-dog-buns-8pk","ing-yeast-instant",      0.005),
    ("sku-d-italiano-hot-dog-buns-8pk","ing-salt-kosher",        0.006),
    ("sku-d-italiano-hot-dog-buns-8pk","ing-milk-whole",         0.040),
    ("sku-d-italiano-hot-dog-buns-8pk","ing-eggs-whole",         0.020),

    # Country Harvest 12 Grain Bread (single 675g sliced loaf)
    ("sku-country-harvest-12-grain-loaf","ing-flour-whole-wheat",0.260),
    ("sku-country-harvest-12-grain-loaf","ing-flour-ap",         0.150),
    ("sku-country-harvest-12-grain-loaf","ing-oats-rolled",      0.040),
    ("sku-country-harvest-12-grain-loaf","ing-flax-seeds",       0.015),
    ("sku-country-harvest-12-grain-loaf","ing-sunflower-seeds",  0.012),
    ("sku-country-harvest-12-grain-loaf","ing-yeast-instant",    0.005),
    ("sku-country-harvest-12-grain-loaf","ing-salt-kosher",      0.008),
]

# Eight seeded retailer orders. Tier mix preserved from original seed.sql:
#   Costco -> bulk staples, Walmart -> staples, Loblaws -> mid, Whole Foods -> premium.
# Dates land mid-week 2026-05/06 to match the existing demo timeframe.
TORONTO_RETAILER_ORDERS: list[dict] = [
    # Costco -- bulk staples
    {"retailer_id": "costco",     "sku_id": "sku-ace-baguette-classic",
     "quantity_units": 12000, "requested_delivery_date": date(2026, 5, 28), "status": "open"},
    {"retailer_id": "costco",     "sku_id": "sku-wonder-classic-white-loaf",
     "quantity_units":  8000, "requested_delivery_date": date(2026, 5, 29), "status": "open"},

    # Walmart -- staples
    {"retailer_id": "walmart",    "sku_id": "sku-country-harvest-12-grain-loaf",
     "quantity_units":  6000, "requested_delivery_date": date(2026, 5, 27), "status": "scheduled"},
    {"retailer_id": "walmart",    "sku_id": "sku-d-italiano-hot-dog-buns-8pk",
     "quantity_units":  9000, "requested_delivery_date": date(2026, 5, 30), "status": "open"},

    # Loblaws -- mid-tier
    {"retailer_id": "loblaws",    "sku_id": "sku-stonefire-original-naan-2pk",
     "quantity_units":  4500, "requested_delivery_date": date(2026, 5, 29), "status": "open"},
    {"retailer_id": "loblaws",    "sku_id": "sku-ace-sourdough-bistro",
     "quantity_units":  3200, "requested_delivery_date": date(2026, 6,  1), "status": "open"},

    # Whole Foods -- premium
    {"retailer_id": "wholefoods", "sku_id": "sku-ace-rosemary-focaccia",
     "quantity_units":  2400, "requested_delivery_date": date(2026, 5, 28), "status": "open"},
    {"retailer_id": "wholefoods", "sku_id": "sku-stonefire-pizza-crust-2pk",
     "quantity_units":  3600, "requested_delivery_date": date(2026, 5, 30), "status": "open"},
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the cascade plan and the new SKUs, then exit.",
    )
    args = parser.parse_args()

    if args.dry_run:
        _print_plan()
        return 0

    new_ids = [s["sku_id"] for s in TORONTO_SKUS]

    with psycopg.connect(DATABASE_URL, autocommit=False) as conn:
        with conn.cursor() as cur:
            # Idempotency check: if every new SKU is already present and
            # none of the legacy IDs remain, this is a no-op re-run.
            cur.execute(
                "SELECT sku_id FROM skus WHERE sku_id = ANY(%s)",
                (list(LEGACY_SKU_IDS),),
            )
            legacy_present = [r[0] for r in cur.fetchall()]

            cur.execute(
                "SELECT sku_id FROM skus WHERE sku_id = ANY(%s)",
                (new_ids,),
            )
            new_present = {r[0] for r in cur.fetchall()}

            if not legacy_present and len(new_present) == len(new_ids):
                print(
                    f"[seed_toronto_skus] All {len(TORONTO_SKUS)} branded SKUs already "
                    f"present and 0 legacy SKUs left -- nothing to do."
                )
                return 0

            # 1) Delete the dependents that FK to legacy SKUs, in FK-safe order.
            cur.execute(
                "DELETE FROM demand_forecasts WHERE sku_id = ANY(%s)",
                (list(LEGACY_SKU_IDS),),
            )
            forecasts_deleted = cur.rowcount

            cur.execute(
                "DELETE FROM retailer_orders WHERE sku_id = ANY(%s)",
                (list(LEGACY_SKU_IDS),),
            )
            orders_deleted = cur.rowcount

            cur.execute(
                "DELETE FROM production_formulas WHERE sku_id = ANY(%s)",
                (list(LEGACY_SKU_IDS),),
            )
            formulas_deleted = cur.rowcount

            cur.execute(
                "DELETE FROM skus WHERE sku_id = ANY(%s)",
                (list(LEGACY_SKU_IDS),),
            )
            skus_deleted = cur.rowcount

            # 2) Insert the 12 branded SKUs.
            sku_rows = [
                {
                    "sku_id":          s["sku_id"],
                    "name":            s["name"],
                    "category":        s["category"],
                    "margin_per_unit": s["margin_per_unit"],
                    "allergen_tags":   s["allergen_tags"],
                    "shelf_life_days": s["shelf_life_days"],
                }
                for s in TORONTO_SKUS
            ]
            cur.executemany(
                """
                INSERT INTO skus
                  (sku_id, name, category, margin_per_unit, allergen_tags, shelf_life_days)
                VALUES
                  (%(sku_id)s, %(name)s, %(category)s, %(margin_per_unit)s,
                   %(allergen_tags)s, %(shelf_life_days)s)
                ON CONFLICT (sku_id) DO NOTHING
                """,
                sku_rows,
            )

            # 3) Insert the production_formulas rows.
            formula_rows = [
                {"sku_id": s, "ingredient_id": i, "kg_per_unit": k}
                for (s, i, k) in TORONTO_FORMULAS
            ]
            cur.executemany(
                """
                INSERT INTO production_formulas (sku_id, ingredient_id, kg_per_unit)
                VALUES (%(sku_id)s, %(ingredient_id)s, %(kg_per_unit)s)
                ON CONFLICT (sku_id, ingredient_id) DO NOTHING
                """,
                formula_rows,
            )

            # 4) Insert the eight seeded retailer_orders.
            cur.executemany(
                """
                INSERT INTO retailer_orders
                  (retailer_id, sku_id, quantity_units, requested_delivery_date, status)
                VALUES
                  (%(retailer_id)s, %(sku_id)s, %(quantity_units)s,
                   %(requested_delivery_date)s, %(status)s)
                """,
                TORONTO_RETAILER_ORDERS,
            )

        conn.commit()

    print(
        f"[seed_toronto_skus] Cleanup deleted: "
        f"{skus_deleted} skus, {formulas_deleted} formulas, "
        f"{orders_deleted} retailer_orders, {forecasts_deleted} demand_forecasts."
    )
    print(
        f"[seed_toronto_skus] Inserted {len(TORONTO_SKUS)} branded SKUs, "
        f"{len(TORONTO_FORMULAS)} formula rows, "
        f"{len(TORONTO_RETAILER_ORDERS)} retailer orders."
    )
    _summarize_by_brand()
    return 0


def _print_plan() -> None:
    print(f"[seed_toronto_skus] Dry run -- {len(TORONTO_SKUS)} new SKUs:")
    for s in TORONTO_SKUS:
        allergens = ",".join(s["allergen_tags"])
        print(
            f"  {s['sku_id']:42s}  {s['brand']:18s}  "
            f"${s['margin_per_unit']:>4.2f}  shelf={s['shelf_life_days']:>2}d  "
            f"[{allergens}]  {s['name']}"
        )
    print(
        f"[seed_toronto_skus] Cascade plan: DELETE dependents of "
        f"{len(LEGACY_SKU_IDS)} legacy SKUs (demand_forecasts -> retailer_orders "
        f"-> production_formulas -> skus), then INSERT "
        f"{len(TORONTO_SKUS)} skus + {len(TORONTO_FORMULAS)} formulas + "
        f"{len(TORONTO_RETAILER_ORDERS)} retailer_orders."
    )
    _summarize_by_brand()


def _summarize_by_brand() -> None:
    counts = Counter(s["brand"] for s in TORONTO_SKUS)
    line = "  ".join(f"{brand}={n}" for brand, n in sorted(counts.items()))
    print(f"[seed_toronto_skus] By brand: {line}")


if __name__ == "__main__":
    raise SystemExit(main())
